# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'libraries/phonon': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'graphics/libkdcraw': '@latest-kf6'
    'education/marble': '@latest-kf6'

Options:
    require-passing-tests-on: [ Linux, FreeBSD ]
