# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'libraries/phonon': '@stable-kf6-qt6'
    'frameworks/karchive': '@stable-kf6-qt6'
    'frameworks/kcompletion': '@stable-kf6-qt6'
    'frameworks/kconfig': '@stable-kf6-qt6'
    'frameworks/kcoreaddons': '@stable-kf6-qt6'
    'frameworks/ki18n': '@stable-kf6-qt6'
    'frameworks/kiconthemes': '@stable-kf6-qt6'
    'frameworks/kjobwidgets': '@stable-kf6-qt6'
    'frameworks/kio': '@stable-kf6-qt6'
    'frameworks/ktextwidgets': '@stable-kf6-qt6'
    'frameworks/kxmlgui': '@stable-kf6-qt6'
    'frameworks/kwidgetsaddons': '@stable-kf6-qt6'
    'frameworks/purpose': '@stable-kf6-qt6'
    'graphics/libkdcraw': '@stable-kf6-qt6'
    'education/marble': '@stable-kf6-qt6'

Options:
    # jzarl: leave Linux and freebsd CI disabled until we have something that compiles:
    #require-passing-tests-on: [ Linux, FreeBSD ]
