# Trigger build 3
---
name: kphotoalbum
confinement: strict
grade: stable
base: core24
adopt-info: kphotoalbum
version: 6.0.1
icon: $CRAFT_PROJECT_DIR/icons/global/32-apps-kphotoalbum.png
apps:
  kphotoalbum:
    command: usr/bin/kphotoalbum
    common-id: org.kde.kphotoalbum.desktop
    desktop: usr/share/applications/org.kde.kphotoalbum.desktop
    extensions:
      - kde-neon-6
    plugs:
      - audio-playback
      - camera
      - home
      - mount-observe
      - network
      - network-bind
      - network-manager-observe
      - removable-media
      - udisks2
      - cups
      - hardware-observe
      - browser-support
    environment:
      KP_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble/plugins;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum/marble$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      DICPATH: "$SNAP/usr/share/hunspell"
      PERL5LIB: "$SNAP/usr/share/perl5"
      LD_LIBRARY_PATH: "$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH"
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin:$PATH
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QT_MEDIA_BACKEND: "ffmpeg"
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble/plugins:$SNAP/usr/lib/x86_64-linux-gnu/plugins:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      QTWEBENGINE_DISABLE_SANDBOX: 1

environment:
  LD_LIBRARY_PATH: "/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vlc:/usr/lib:/lib"
  VLC_PLUGIN_PATH: "/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vlc/plugins"

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum
  /usr/share/marble:
    symlink: $SNAP/usr/share/marble

package-repositories:
-   type: apt
    components:
    - main
    suites:
    - noble
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: https://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com

plugs:
  hunspell-dictionaries:
    content: hunspell-dictionaries
    interface: content
    target: "$SNAP/usr/share/hunspell"
    default-provider: hunspell-dictionaries
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404

slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kphotoalbum
        bus: session

parts:
  marble:
    source: https://invent.kde.org/education/marble.git
    source-branch: release/25.08
    plugin: cmake
    build-packages:
      - libpulse0
      - rsync
    stage-packages:
      - libpulse0
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - --log-level=STATUS
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DCMAKE_FIND_ROOT_PATH="/snap/ffmpeg-2404-sdk/current;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current"
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    build-environment: &build-environment
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
      - LD_LIBRARY_PATH: "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
      - DICPATH: "$CRAFT_STAGE/usr/share/hunspell"
    prime:
      - -usr/bin/rsync
  libkdcraw:
    after:
      - marble
    plugin: cmake
    source: https://invent.kde.org/graphics/libkdcraw.git
    source-branch: release/25.08
    build-packages:
      - libraw-dev
    stage-packages:
      - libraw23t64
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    build-environment: *build-environment
  kdegraphics-thumbnailers:
    after:
      - libkdcraw
    plugin: cmake
    source: https://invent.kde.org/graphics/kdegraphics-thumbnailers.git
    source-branch: release/25.08
    # build-packages:
      # - libqmobipocket6-dev
    # stage-packages:
      # - libqmobipocket6-2
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DDISABLE_MOBIPOCKET=ON
    build-environment: *build-environment
  kphotoalbum:
    after:
      - marble
      - libkdcraw
      - kdegraphics-thumbnailers
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - libexiv2-dev
      - libjpeg-dev
      - libvlc-dev
      - libvlccore-dev
      # - qt6-phonon-dev
      # - qt6-phonon-backend-vlc
    stage-packages:
      - libasound2
      - libasound2-data
      - libasound2-plugins
      - libjpeg8
      - libvlc-bin
      # - qt6-phonon
      # - qt6-phonon-backend-vlc
      - exif
      # - kdegraphics-thumbnailers
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_TESTING=OFF
      - -DBUILD_TESTING=OFF
      - -DKDE_SKIP_TEST_SETTINGS=ON
      - -DBUILD_TESTING=OFF
      - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kde-qt6-core24-sdk/current\\;/snap/kf6-core24-sdk/current/usr"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kde-qt6-core24-sdk/current\\;/snap/kf6-core24-sdk/current/usr"
    build-environment: *build-environment
    parse-info:
      - usr/share/metainfo/org.kde.kphotoalbum.appdata.xml
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kphotoalbum]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kdegraphics-thumbnailers
      - kphotoalbum
      - libkdcraw
      - marble
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - ffmpeg-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
