# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kphotoalbum
confinement: strict
grade: stable
base: core24
adopt-info: kphotoalbum
version: 6.2.0
icon: $CRAFT_PROJECT_DIR/icons/global/32-apps-kphotoalbum.png
apps:
  kphotoalbum:
    command: usr/bin/kphotoalbum
    common-id: org.kde.kphotoalbum.desktop
    desktop: usr/share/applications/org.kde.kphotoalbum.desktop
    extensions:
      - kde-neon-6
    plugs:
      - audio-playback
      - camera
      - home
      - mount-observe
      - network
      - network-bind
      - network-manager-observe
      - removable-media
      - udisks2
      - cups
      - hardware-observe
      - browser-support
    environment:
      KP_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotoalbum;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble/plugins;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins;$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum/marble$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      DICPATH: "$SNAP/usr/share/hunspell"
      PERL5LIB: "$SNAP/usr/share/perl5"
      LD_LIBRARY_PATH: "/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vlc:/usr/lib:/lib"
      VLC_PLUGIN_PATH: "/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vlc/plugins"
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin:$PATH
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QT_MEDIA_BACKEND: "ffmpeg"
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble/plugins:$SNAP/usr/lib/x86_64-linux-gnu/plugins:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins"
      QTWEBENGINE_DISABLE_SANDBOX: 1

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/marble
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/plugins/kphotalbum
  /usr/share/marble:
    symlink: $SNAP/usr/share/marble

plugs:
  hunspell-dictionaries:
    content: hunspell-dictionaries
    interface: content
    target: "$SNAP/usr/share/hunspell"
    default-provider: hunspell-dictionaries
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404

slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kphotoalbum
    bus: session

parts:
  wayland:
    source: https://gitlab.freedesktop.org/wayland/wayland.git
    source-branch: 1.23
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - meson
      - pkgconf
      - xsltproc
      - xmlto
      - libexpat1-dev
      - libffi-dev
      - libxml2-dev
      - doxygen
      - graphviz
    build-environment:
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kde-qt6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kf6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
  wayland-protocols:
    after:
      - wayland
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: 1.47
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libwayland-dev
      - meson
      - pkgconf
    build-environment:
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kde-qt6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kf6-core24-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
  libplasma:
    after: [wayland-protocols]
    source: https://invent.kde.org/plasma/libplasma.git
    source-branch: Plasma/6.6
    plugin: cmake
    build-packages:
      - libpulse0
      - libxkbcommon-dev
      - rsync
    stage-packages:
      - libpulse0
      - libxkbcommon0
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    prime:
      - -usr/bin/rsync
  marble:
    after:
      - libplasma
    source: https://invent.kde.org/education/marble.git
    source-branch: master
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libpulse0
      - rsync
      - libshp-dev
      - libgps-dev
      - libwlocate-dev
      - libabsl-dev
      - libprotobuf-dev
      - protobuf-compiler
      - pkg-config
      - libdrm2
    stage-packages:
      - libpulse0
      - libshp4
      - libgps30t64
      - libwlocate0
      - libabsl20220623t64
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
    override-pull: |
        craftctl default
        patch -p0 < ${SNAPCRAFT_PROJECT_DIR}/snap/local/patches/disable_broken_osm_plugin.patch
    stage:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libz.so*
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
    build-environment:
      - DICPATH: "$CRAFT_STAGE/usr/share/hunspell"
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    prime:
      - -usr/bin/rsync
  libkdcraw:
    after:
      - marble
    plugin: cmake
    source: https://invent.kde.org/graphics/libkdcraw.git
    source-branch: release/25.12
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libraw-dev
    stage-packages:
      - libraw23t64
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
  kdegraphics-thumbnailers:
    after:
      - libkdcraw
    plugin: cmake
    source: https://invent.kde.org/graphics/kdegraphics-thumbnailers.git
    source-branch: release/25.12
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DDISABLE_MOBIPOCKET=ON
  kphotoalbum:
    after:
      - marble
      - libkdcraw
      - kdegraphics-thumbnailers
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
      - cmake
    build-packages:
      - libexiv2-dev
      - libjpeg-dev
      - libvlc-dev
      - libvlccore-dev
    stage-packages:
      - libasound2
      - libasound2-data
      - libasound2-plugins
      - libjpeg8
      - libvlc-bin
      - exif
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_TESTING=OFF
      - -DBUILD_TESTING=OFF
      - -DKDE_SKIP_TEST_SETTINGS=ON
      - -DBUILD_TESTING=OFF
    parse-info:
      - usr/share/metainfo/org.kde.kphotoalbum.appdata.xml
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
    build-environment:
      - PATH: /snap/cmake/current/usr/bin:$PATH
  gpu-2404:
    after: [kphotoalbum]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kdegraphics-thumbnailers
      - kphotoalbum
      - libkdcraw
      - marble
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - ffmpeg-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
