#!/bin/sh
#select *, UTC_TIMESTAMP() from test;

DBNAME="kphotoalbum"
USER=""
PASSWD=""

function usage {
	echo "Usage: $0 [-d db_name] [-u username] [-p [password]]"
}

while [ $# -ge 1 ]; do
	if [ "$1" = "-d" ]; then
		if [ -n "$2" ]; then
			DBNAME="$2"
			shift
		else
			usage
		fi
	elif [ "$1" = "-u" ]; then
		if [ -n "$2" ]; then
			USER="$2"
			shift
		else
			usage
		fi
	elif [ "$1" = "-p" ]; then
		if [ -n "$2" ]; then
			PASSWD="$2"
			shift
		else
			read -p "Enter password: " -s PASSWD
			echo
		fi
	else
		usage
	fi
	shift
done

opts=""
[ -n "$USER" ] && opts+=" -u $USER"
[ -n "$PASSWD" ] && opts+=" -p$PASSWD"

echo y | mysqladmin $opts drop "$DBNAME" &>/dev/null

mysqladmin $opts create "$DBNAME" || {
	echo "Error creating database $DBNAME" 1>&2
	exit 1
}

mysql $opts "$DBNAME" << EOF
CREATE TABLE membergroup
(
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   groupname varchar(128) NOT NULL,
   category varchar(128) NOT NULL,
   member varchar(128) NOT NULL
);

CREATE TABLE imageinfo 
(
  fileId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  label varchar(255),
  description TEXT,
  startDate DATETIME,
  endDate DATETIME,
  angle INT,
  md5sum varchar(64),
  width INT,
  height INT,
  INDEX( startDate ),
  INDEX( endDate )
);

CREATE TABLE imagecategoryinfo
(
  fileId INT,
  categoryId INT,
  value varchar(255),
  INDEX(fileId),
  INDEX(categoryId)
);

CREATE TABLE categorysetup 
(
  categoryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,   
  category varchar(255),
  viewtype INT,
  viewsize INT,
  icon varchar(128),
  showIt bool
);

CREATE TABLE sortorder 
(
  fileId INT PRIMARY KEY,
  fileName varchar(255),
  idx INT
);

CREATE TABLE categorysortorder
(
  idx INT,
  categoryId INT,
  item varchar(255)
);
EOF

echo show tables | mysql $opts "$DBNAME"
