#!/bin/sh
mysql -u root kphotoalbum << EOF

insert into membergroup( groupname, category, member ) values
  ("Denmark", "Locations", "Esbjerg" ),
  ("Denmark", "Locations", "Pool Club" ),
  ("USA", "Locations", "Chicago" ),
  ("USA", "Locations", "Grand Canyon" ),
  ("USA", "Locations", "Santa Clara" ),
  ("Pets", "Persons", "Donna" ),
  ("Pets", "Persons", "Spiff" );


insert into sortorder( fileId, fileName, idx ) values
  ( 1, "img001.jpg", 1 ),
  ( 2, "img002.jpg", 2 ),
  ( 3, "img003.jpg", 3 ),
  ( 4, "img004.jpg", 4 ),
  ( 5, "img005.jpg", 5 ),
  ( 6, "img006.jpg", 6 ),
  ( 7, "img007.jpg", 7 ),
  ( 8, "img008.jpg", 8 ),
  ( 9, "img009.jpg", 9 ),
  ( 10, "img010.jpg", 10 ),
  ( 11, "img011.jpg", 11 ),
  ( 12, "img012.jpg", 12 ),
  ( 13, "img013.jpg", 13 ),
  ( 14, "img014.jpg", 14 ),
  ( 15, "img015.jpg", 15 ),
  ( 16, "img016.jpg", 16 ),
  ( 17, "img017.jpg", 17 ),
  ( 18, "img018.jpg", 18 ),
  ( 19, "img019.jpg", 19 ),
  ( 20, "img020.jpg", 20 ),
  ( 21, "img021.jpg", 21 ),
  ( 22, "img022.jpg", 22 ),
  ( 23, "img023.jpg", 23 ),
  ( 24, "img024.jpg", 24 );


insert into categorysetup
  set viewtype=0, viewsize=0, icon="password", category="Keywords",
      categoryId=1, showIt=1;

insert into categorysetup
  set viewtype=0, viewsize=0, icon="network", category="Locations", 
      categoryId=2, showIt=1;

insert into categorysetup
  set viewtype=1, viewsize=1, icon="personal", category="Persons", 
      categoryId=3, showIt=1;

insert into categorysetup
  set viewtype=0, viewsize=0, icon="folder", category="Folder", 
      categoryId=4, showIt=0;

insert into categorysetup
  set viewtype=0, viewsize=0, icon="cookie", category="Tokens", 
      categoryId=5, showIt=1;




insert into imageinfo
  set width=569, height=800, md5sum="570cb78b687b85f1e840b276868832aa", fileId=16, label="img016", angle=0, description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=549, height=800, md5sum="301ed80fa98e9388656cd06dc027463b",
fileId=17 , label="img017", angle=0, description="When I was 17-20 years
old I considered myself a new-waver, and therefore looked like this most of
the time. My dirvers license (which I'll have till I'm 60 years old), does
still contain such an image ;-)", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=550,   md5sum="b9117748687c4aa5375e103cc05d5ee8",  fileId=18 , label="img018", angle=0,    description="Getting the hair standing like this took almost 20 minues each and every morning, plus 10 minutes fix up during lunch break from school.", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=550,   md5sum="5a5d3f200abdaa8863d9d1350cd1cc0b",  fileId=19 , label="img019", angle=0,    description="Spiff is enjoying a box of beers, or rather a beer box ;-)", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=550,    height=800,   md5sum="4ce27d23f69210d809bd2e8e0f188151",  fileId=20 , label="img020", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=551,   md5sum="5216980dd2b315a2f022fcaf1271f6bc",  fileId=21 , label="img021", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="2bddc648abe5cb9cac8d299d68015081",  fileId=24 , label="img024", angle=0,    description="Just in case you haven't figure out what this is - its sugar ;-)", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=535,   md5sum="ca5d49e569a7061544fbb439b1522e06",  fileId=13 , label="img013", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=535,   md5sum="7b3f9984fb669bd57c807370ea5746d9",  fileId=14 , label="img014", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=535,   md5sum="0890cc6feef62fb62b417aaf403d390d",  fileId=15 , label="img015", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="252228ba88fa9fc6ecac30bcca99141e",  fileId=1 , label="img001", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="5d8af651aa3491765bbe8a08a475cc3e",  fileId=2 , label="img002", angle=0,    description="Its not obvious, but the main focus of this picture is Donna, whos nose you can see in the middle of the picture.", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="b8915701a21c6fa71c1c9c560664a371",  fileId=3 , label="img003", angle=0,    description="I'm in no way &lt;em>a shark&lt;/em> at pool, but I enjoy a game once in a while. I've been a board member of a pool club for almost 2 years, which unfortunately means that I'm more often in boardmeetings than at the pool tables.", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="8d2d351e523dd0e5c54db76d321b5be6",  fileId=4 , label="img004", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=600,    height=800,   md5sum="3354ef8dc72be960d8add460998f28a0",  fileId=5 , label="img005", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="be19fc1a4af1e4a31fff66c7c58a11dd",  fileId=6 , label="img006", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=600,    height=800,   md5sum="40e6335090bb9a4ab316eb969369cd62",  fileId=7 , label="img007", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="897a960470fc2557cabe9b7371274ec9",  fileId=8 , label="img008", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="ec8fe2b7d784813379042e83e0f7aaa6",  fileId=9 , label="img009", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="b9b3da4f9a225e5bff296f8075828eff",  fileId=10 , label="img010", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="92f54b52ba44869e620d713f1b0420a3",  fileId=11 , label="img011", angle=0,    description="Anne Helene and I had a lot of fun playing with the automatic timer on our digital camera.", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=600,   md5sum="aca7182ae0ae819e48ba7221afb4559c",  fileId=12 , label="img012", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=800,    height=551,   md5sum="5ccc31e822e0638740c8296c2b9637dc",  fileId=22 , label="img022", angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";

insert into imageinfo
  set width=551,    height=800,
md5sum="bdc4b7ed37734d14c909162f101e78e3",  fileId=23 , label="img023",
angle=0,    description="", startDate = "1990-01-01 12:33", endDate = "2000-01-01 19:27";








insert into imagecategoryinfo
  set fileId=16,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=17,categoryId=1, value="new wave" ;

insert into imagecategoryinfo
  set fileId=17,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=18,categoryId=1, value="new wave" ;

insert into imagecategoryinfo
  set fileId=18 ,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=19 ,categoryId=1, value="beers" ;

insert into imagecategoryinfo
  set fileId=19 ,categoryId=3, value="Spiff" ;

insert into imagecategoryinfo
  set fileId=20 ,categoryId=3, value="Spiff" ;

insert into imagecategoryinfo
  set fileId=21 ,categoryId=3, value="Spiff" ;

insert into imagecategoryinfo
  set fileId=24 ,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=24 ,categoryId=2, value="Santa Clara" ;

insert into imagecategoryinfo
  set fileId=24,categoryId=3, value="Anne Helene" ;

insert into imagecategoryinfo
  set fileId=13,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=13 ,categoryId=2, value="Grand Canyon" ;

insert into imagecategoryinfo
  set fileId=13,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=13,categoryId=3, value="Anne Helene" ;

insert into imagecategoryinfo
  set fileId=14,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=14,categoryId=2, value="Grand Canyon" ;

insert into imagecategoryinfo
  set fileId=15,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=15,categoryId=2, value="Grand Canyon" ;

insert into imagecategoryinfo
  set fileId=15,categoryId=3, value="Anne Helene" ;

insert into imagecategoryinfo
  set fileId=1,categoryId=1, value="Anne Helene's 30 years birthday" ;

insert into imagecategoryinfo
  set fileId=1,categoryId=2, value="Esbjerg" ;

insert into imagecategoryinfo
  set fileId=1,categoryId=3, value="Donna" ;

insert into imagecategoryinfo
  set fileId=2,categoryId=1, value="Anne Helene's 30 years birthday" ;

insert into imagecategoryinfo
  set fileId=2,categoryId=2, value="Esbjerg" ;

insert into imagecategoryinfo
  set fileId=2,categoryId=3, value="Donna" ;

insert into imagecategoryinfo
  set fileId=3,categoryId=1, value="Anne Helene's 30 years birthday" ;

insert into imagecategoryinfo
  set fileId=3,categoryId=2, value="Pool Club" ;

insert into imagecategoryinfo
  set fileId=3,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=4,categoryId=1, value="Anne Helene's 30 years birthday" ;

insert into imagecategoryinfo
  set fileId=4,categoryId=2, value="Pool Club" ;

insert into imagecategoryinfo
  set fileId=4,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=05,categoryId=2, value="Chicago" ;

insert into imagecategoryinfo
  set fileId=06,categoryId=2, value="Chicago" ;

insert into imagecategoryinfo
  set fileId=06,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=07,categoryId=1, value="silo falls over" ;

insert into imagecategoryinfo
  set fileId=07,categoryId=2, value="Esbjerg" ;

insert into imagecategoryinfo
  set fileId=08,categoryId=1, value="silo falls over" ;

insert into imagecategoryinfo
  set fileId=08,categoryId=2, value="Esbjerg" ;

insert into imagecategoryinfo
  set fileId=09,categoryId=1, value="silo falls over" ;

insert into imagecategoryinfo
  set fileId=09,categoryId=2, value="Esbjerg" ;

insert into imagecategoryinfo
  set fileId=10,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=10,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=11,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=11,categoryId=2, value="Mallorca" ;

insert into imagecategoryinfo
  set fileId=11,categoryId=3, value="Anne Helene" ;

insert into imagecategoryinfo
  set fileId=11,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=12,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=12,categoryId=2, value="Mallorca" ;

insert into imagecategoryinfo
  set fileId=12,categoryId=3, value="Jesper" ;

insert into imagecategoryinfo
  set fileId=22,categoryId=3, value="Donna" ;

insert into imagecategoryinfo
  set fileId=23,categoryId=1, value="holiday" ;

insert into imagecategoryinfo
  set fileId=23,categoryId=2, value="Rhodos" ;

insert into imagecategoryinfo
  set fileId=23,categoryId=3, value="Anne Helene" ;


insert into categorysortorder (idx, categoryId, item) value
( 1, 1, "beers" ),
( 2, 1, "holiday" ),
( 3, 1, "new wave" ),
( 4, 1, "silo falls over" ),
( 5, 1, "Anne Helene's 30 years birthday" ),
( 6, 2, "Santa Clara" ),
( 7, 2, "Mallorca" ),
( 8, 2, "Grand Canyon" ),
( 9, 2, "Pool Club" ),
( 10,2,  "Chicago" ),
( 11,2,  "Rhodos" ),
( 12,2,  "Esbjerg" ),
( 13, 3, "Spiff" ),
( 14, 3, "Anne Helene" ),
( 15, 3, "Jesper" ),
( 16, 3, "Donna" )
