#!/bin/bash
# SPDX-FileCopyrightText: 2019 Johannes Zarl-Zierl <johannes@zarl-zierl.at>
# SPDX-License-Identifier: BSD-2-Clause
###
# Check for untracked C++ source files.
###

set -e

if [[ -z "$CHECK_UNTRACKED" ]]
then
	CHECK_UNTRACKED=$(git config --bool --get kpa.checkUntracked || echo true)
fi
if [[ "$CHECK_UNTRACKED" == false ]]
then
	exit 0
fi

retval=0
untracked_files=$(git status -s | grep '^?? ' | grep '\.\(cpp\|h\)' | sed 's/^.../   /')
if [[ -n "$untracked_files" ]]
then
	printf "Untracked files:\n$untracked_files\n"
	printf "** You can suppress this check by setting 'git config kpa.checkUntracked false'\n"
	printf "** or by setting the environment variable CHECK_UNTRACKED=false\n"
	exit 1
fi
